Fix comment error when nested
withastro/prettier-plugin-astro pull request #109
Opened 2022-01-15 23:40 UTC by antonyfaris

## Changes

Fixes #81 

## Testing

I added a test for nested comments.

## Docs

2022-01-15 23:41 UTC, antonyfaris commented on src/printer.ts
> +  if (!isPreTagContent(path) && !isMarkdownSubDoc && node.type === 'Fragment') {
I think it should only run once at the top level.

2022-01-15 23:42 UTC, antonyfaris commented on src/utils.ts
> +      if (commentNode) {
It checks if there is a node before trying to attach the comment.

2022-01-18 15:19 UTC, jonathantneal approved these changes
Seem like good improvements. The tests 🤌 make it easy to approve.

2022-01-18 16:38 UTC, natemoo-re approved these changes
Looks great, thanks!

2022-01-18 18:31 UTC, boehs commented on src/utils.ts
> +        util.addLeadingComment(commentNode, comment);
```suggestion
      const commentNode = node.children[next];
      if (commentNode) {
        util.addLeadingComment(commentNode, node.children[n]);
```

Comment is only used in one place, so it *may* make more sense to include it directly in the function. This is at the cost of clarity, so both ways work

2022-01-18 18:36 UTC, boehs requested changes

2022-01-18 18:36 UTC, boehs commented on src/utils.ts
> +        util.addLeadingComment(commentNode, comment);
```suggestion
      const commentNode = node.children[next];
      if (commentNode) {
        const comment = node.children[n];
        util.addLeadingComment(commentNode, comment);
```

2022-01-18 20:05 UTC, merged