chore(package.json): remove pnpm from engines
withastro/prettier-plugin-astro pull request #362
Opened 2023-07-20 11:24 UTC by youkwhd

## Changes

removes pnpm from engines, as it is not a javascript engine.

![screenshot: warning from package manager](https://github.com/withastro/prettier-plugin-astro/assets/74759624/6e214e60-2e69-4261-9c58-7560e9595722)

## Testing

ran `<pkg-manager> test`

most likely a typo fix

## Docs

typo fix

2023-07-20 21:55 UTC, Princesseuh requested changes

2023-07-20 21:55 UTC, Princesseuh commented on .changeset/six-spies-roll.md
> +'prettier-plugin-astro': minor
Should be a patch 
```suggestion
'prettier-plugin-astro': patch
```

2023-07-21 15:47 UTC, youkwhd commented on .changeset/six-spies-roll.md
> +'prettier-plugin-astro': minor
sorry for the delay

2023-07-21 15:49 UTC, Princesseuh commented on .changeset/six-spies-roll.md
> +'prettier-plugin-astro': minor
No worries, thank you for contributing!

2023-07-21 15:49 UTC, Princesseuh approved these changes

2023-07-21 15:50 UTC, merged